color0 #121316
color1 #ffb4ab
color2 #9bcaff
color3 #bac8db
color4 #d5bee5
color5 #9bcaff
color6 #bac8db
color7 #e2e2e6
color8 #8c9199
color9 #ffb4ab
color10 #9bcaff
color11 #bac8db
color12 #d5bee5
color13 #9bcaff
color14 #bac8db
color15 #e2e2e6

cursor                #e2e2e6
cursor_text_color     #121316
background            #121316
foreground            #e2e2e6
selection_foreground  #c2c7cf
selection_background  #42474e
active_border_color   #9bcaff
inactive_border_color #42474e
url_color             #9bcaff

active_tab_foreground   #003256
active_tab_background   #9bcaff
inactive_tab_foreground #c2c7cf
inactive_tab_background #42474e
cursor_trail_color      #c2c7cf
