cursor            #ffb4a4
cursor_text_color #640e00

foreground            #f9dcd6
background            #180b08
selection_foreground  #4a2812
selection_background  #f3ba9b
url_color             #f3ba9b

#: black 000000 767676
color0  #1e100d
color8  #42312d
#: red cc0403 f2201f
color1  #9e3116
color9  #e97e64
#: green 19cb00 23fd00
color2  #f3ba9b
color10 #ffdbc9
#: yellow cecb00 fffd00
color3  #f6bb7e
color11 #ffdcbc
#: blue 0d73cc 1a8fff
color4  #8c1700
color12 #ffb4a4
#: magenta cb1ed1 fd28ff
color5  #643d26
color13 #f3ba9b
#: cyan 0dcdcd 14ffff
color6  #663e0a
color14 #f6bb7e
#: white dddddd ffffff
color7  #dcc1bb
color15 #f9dcd6

mark1_foreground #3e0500
mark1_background #ffdad3
mark2_foreground #311302
mark2_background #ffdbc9
mark3_foreground #2c1600
mark3_background #ffdcbc

active_tab_foreground #640e00
active_tab_background #ffb4a4
inactive_tab_foreground #ffdad3
inactive_tab_background #8c1700

active_border_color #ffb4a4
inactive_border_color #640e00
# bell_border_color #ff5a00
