# Font
font_family      JetBrainsMono Nerd Font
font_size 11.0

# cursor trail
cursor_blink_interval 0

# Cursor
# cursor_text_color background
cursor_shape block
cursor_shape_unfocused hollow
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0

# Padding (why weird value? consistency with foot)
window_margin_width 2

# Ask before closing the OS window to avoid accidental exits
confirm_os_window_close 1

# Use fish shell
shell fish

# Copy for normies
map ctrl+c       copy_or_interrupt

# Zoom
map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1

map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+kp_subtract       change_font_size all -1

map ctrl+0 change_font_size all 0
map ctrl+kp_0 change_font_size all 0

# enable window swallow
# enable_swallowing yes

copy_on_select no
strip_trailing_spaces smart

# 设置边框宽度
draw_minimal_borders yes
window_border_width 1pt

window_margin_width 0
window_padding_width 4

hide_window_decorations no

# --- bar布局 ---
tab_bar_min_tabs            2
tab_bar_edge                bottom
tab_bar_style               custom
# tab_powerline_style         slanted  (custom mode 默认 angled)
# tab_powerline_style         angled  (回到默认)
tab_title_template "{index}: {title[:12]}{'  :{}'.format(num_windows) if num_windows > 1 else ''}"

# key mapping

# ======================
# 窗口管理相关快捷键设置
# ======================

#  新建标签页
map ctrl+shift+i new_tab

# 启用 splits 布局
enabled_layouts splits:split_axis=horizontal

# 切换到左边的标签页 (Previous Tab)
map ctrl+shift+h previous_tab

# 切换到右边的标签页 (Next Tab)
map ctrl+shift+l next_tab

# 分割窗口
map alt+s launch --location=hsplit --cwd=current
map alt+v launch --location=vsplit --cwd=current

# 使用 Alt + h/j/k/l 在窗口间移动焦点
map alt+k neighboring_window up
map alt+j neighboring_window down
map alt+h neighboring_window left
map alt+l neighboring_window right

# 使用 Alt + Shift + h/j/k/l 移动当前窗口本身的位置
map alt+shift+k move_window up
map alt+shift+j move_window down
map alt+shift+h move_window left
map alt+shift+l move_window right

# 使用 Alt + Shift + h/j/k/l 移动当前窗口本身的位置
map alt+shift+k move_window up
map alt+shift+j move_window down
map alt+shift+h move_window left
map alt+shift+l move_window right

# 使用 Alt + 方向键 调整窗口大小
map alt+up       resize_window taller
map alt+down     resize_window shorter 3
map alt+right    resize_window narrower
map alt+left    resize_window wider 3

# BEGIN_KITTY_THEME
# TokyoNight
include themes/tokyonight_night.conf
# END_KITTY_THEME
#

shell_integration enabled

map alt+q close_window_with_confirmation
map alt+n launch --stdin-source=@screen_scrollback --type=overlay nvim -c "setlocal buftype=nofile bufhidden=hide noswapfile" -c "normal G" -
scrollback_lines 10000
scrollback_pager_history_size 200
