# =============================================================================
# Shortcuts - custom command shortcuts
# =============================================================================

# Set prefix to Ctrl+a (like screen)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split panes (keep current working directory)
bind -n M-s split-window -v -c "#{pane_current_path}"
bind -n M-v split-window -h -c "#{pane_current_path}"

# Copy mode (vim-style)
set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
