require("modules/general")
require("modules/keybinding")
require("modules/gestures")
require("modules/animations")
require("modules/startups")
require("modules/windowrules")
require("modules/monitor")
require("hypr-vars")

hl.env("QT_IM_MODULE", "fcitx")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("SDL_IM_MODULE", "fcitx")
hl.env("GLFW_IM_MODULE", "ibus")
