-- Material 3 colors + Hyprland visual bindings — generated by matugen

local M = {}

M.image = "{{image}}"
<* for name, value in colors *>
M.{{name}} = "rgba({{value.default.hex_stripped}}ff)"
<* endfor *>

-- pywal compatibility aliases
M.foreground = M.on_background
M.color0  = M.surface_container_lowest
M.color1  = M.error
M.color2  = M.tertiary
M.color3  = M.secondary
M.color4  = M.primary
M.color5  = M.tertiary
M.color6  = M.secondary
M.color7  = M.on_surface_variant
M.color8  = M.outline
M.color9  = M.primary
M.color10 = M.tertiary
M.color11 = M.secondary_container
M.color12 = M.primary_container
M.color13 = M.tertiary_container
M.color14 = M.secondary
M.color15 = M.on_surface

hl.config({
	general = {
		["col.active_border"] = { colors = { M.primary, M.tertiary }, angle = 45 },
		["col.inactive_border"] = M.surface_container_high,
	},
	decoration = {
		shadow = {
			color = M.shadow,
		},
	},
	group = {
		col = {
			border_active = M.primary,
			border_inactive = M.surface_container_high,
			border_locked_active = M.tertiary,
			border_locked_inactive = M.surface_container,
		},
	},
})

return M
