submap=cursor

# 启动 wl-kbptr
# bind =,a,exec,wl-kbptr -o modes=floating,click -o mode_floating.source=detect

# 方向微调（使用 wlrctl）
binde=,j,exec,wlrctl pointer move 0 10
binde=,k,exec,wlrctl pointer move 0 -10
binde=,l,exec,wlrctl pointer move 10 0
binde=,h,exec,wlrctl pointer move -10 0

binde=shift,j,exec,wlrctl pointer move 0 40
binde=shift,k,exec,wlrctl pointer move 0 -40
binde=shift,l,exec,wlrctl pointer move 40 0
binde=shift,h,exec,wlrctl pointer move -40 0

# 鼠标点击（使用 wlrctl）
bind=,s,exec,wlrctl pointer click left
bind=,d,exec,wlrctl pointer click middle
bind=,f,exec,wlrctl pointer click right
