source=~/.config/hypr/keybinds.conf
source=~/.config/hypr/startups.conf
source=~/.config/hypr/animations.conf
source=~/.config/hypr/windowsrules.conf
source=~/.config/hypr/monitor.conf
source=~/.config/hypr/cursor.conf
# ---- monitors ----

# monitor=eDP-1,disable
# monitor = DP-2, highres, auto, 1.3333
# unscale XWayland
xwayland {
  force_zero_scaling = true
}

general {

            gaps_in = 5
            gaps_out = 10
            border_size = 3
            resize_on_border = true
            allow_tearing = false
            layout = dwindle
}
decoration {
    rounding = 20
    rounding_power=2
        blur {
            enabled = true
                size = 5
                passes = 1
                new_optimizations = true
                xray = false
                popups = true
        }
    shadow {
        enabled = true
            range = 4
            render_power = 3
            color = rgba(1a1a1aee)
    }
}

input{
    touchpad {
        disable_while_typing = true
    }
	repeat_rate=60
	repeat_delay=400
}
group{

    merge_groups_on_drag = true
    merge_groups_on_groupbar = true
    merge_floated_into_tiled_on_groupbar = true
    col.border_active = 0xee88c0d0
    col.border_inactive = 0xee4c566a
    col.border_locked_active = 0xeeff6666
    col.border_locked_inactive = 0xee5e81ac

    groupbar {
        # 启用组栏
        enabled = true

        font_family =
        font_size = 18
        height = 20
        scrolling = true
        render_titles = true
        text_offset = 0
        text_color = 0xffffffff
        text_color_inactive = 0xddffffff
        col.inactive = 0xee3b4252
        col.locked_active = 0xeeab2a2a
        col.locked_inactive = 0xee4c566a
        indicator_height = 3
        indicator_gap = 0
        rounding = 3
        gradients = false
        gaps_in = 2
        gaps_out = 2
    }
}

binds {
	drag_threshold=20 # Fire a dray event only after dragging for more than 20 px
	movefocus_cycles_fullscreen=true
}
misc{
	enable_swallow=true
    initial_workspace_tracking = 1
    vrr = 0
}

# source = /home/tohno/.config/hypr/noctalia/noctalia-colors.conf  # disabled: managed by matugen
source = ~/.cache/matugen/hypr-vars.conf
source = ~/.cache/matugen/hyprland-bindings.conf
