windowrule = opacity 0.8, tag:term

windowrule = opacity 0.8, class:kitty
windowrule = float,noblur,noborder,norounding,xwayland:1

# Filechooser
windowrule = float,move 50% 30%,size 50% 50%, title:filechooser

# anki
windowrule = float, class:anki
