{
  config,
  lib,
  pkgs,
  ...
}:
let
  home = config.home.homeDirectory;
  sshKey = "${home}/.ssh/id_ed25519";
  ageKeyFile = "${home}/.config/sops/age/keys.txt";
  ageKeyDir = dirOf ageKeyFile;
in
{
  sops.defaultSopsFile = ../../secrets/keys.yaml;
  sops.defaultSopsFormat = "yaml";

  # Decrypt using the bootstrap ssh key directly (imported as an age identity).
  sops.age.sshKeyPaths = [ sshKey ];
  # Manually-derived age key file (generated by the activation script below).
  sops.age.keyFile = ageKeyFile;
  # We derive the key ourselves from the ssh key, so don't let sops-nix
  # generate an unrelated random one.
  sops.age.generateKey = false;

  # Derive the age private key from the ssh private key so that manual `sops`
  # CLI usage works too. Runs after writeBoundary (so $HOME is writable) and
  # before the sops-nix activation entry (which restarts the decrypting
  # systemd service).
  home.activation.generateSopsAgeKey = lib.hm.dag.entryBetween [ "sops-nix" ] [ "writeBoundary" ] ''
    if [[ ! -f "${sshKey}" ]]; then
      ${pkgs.coreutils}/bin/printf '\033[1;31m%s\033[0m\n' \
        "[sops] WARNING: ssh private key ${sshKey} not found; cannot derive age key. Copy your bootstrap key there and re-run home-manager switch." >&2
    else
      run ${pkgs.coreutils}/bin/mkdir -p "${ageKeyDir}"
      run ${pkgs.ssh-to-age}/bin/ssh-to-age -private-key -i "${sshKey}" -o "${ageKeyFile}"
      run ${pkgs.coreutils}/bin/chmod 600 "${ageKeyFile}"
    fi
  '';
}
