{
  config,
  lib,
  pkgs,
  ...
}:
let
  home = config.home.homeDirectory;
  ageKeyFile = "${home}/.config/sops/age/keys.txt";
in
{
  sops.defaultSopsFile = ../../secrets/keys.yaml;
  sops.defaultSopsFormat = "yaml";

  # Generated by the NixOS activation script from /etc/ssh/ssh_host_ed25519_key.
  sops.age.keyFile = ageKeyFile;
  sops.age.generateKey = false;
}
